services:
  request-logger:
    build: .
    container_name: antenna
    ports:
      - "3000:3000"
    volumes:
      - ./cache:/app/cache
      - ./assets:/app/assets
    environment:
      - PORT=3000
      - NODE_ENV=production
    restart: unless-stopped
